### ISSUE TITLE
CRUD operation on Damage entity

### ISSUE THREAD

**Issue by st55774** [st55774/KST-NNPRO-Bezpecnost-zeleznic#13]
Create controller (API) contains CRUD operation for Damage entity:

/Users/ondrejchrbolka/Fei/Studium/NNPRO/KST-NNPRO-Bezpecnost-zeleznic/src/main/java/cz/semprace/bezpecnostzeleznic/model/Damage.java

**Comment by Domel303** [comment]
resolved in commit https://github.com/st55774/KST-NNPRO-Bezpecnost-zeleznic/commit/779d7c1c78619201129d2810dadcd3b701d19a9a
