### ISSUE TITLE
CRUD operation on SecurityIncident entity

### ISSUE THREAD

**Issue by st55774** [st55774/KST-NNPRO-Bezpecnost-zeleznic#14]
Create controller (API) contains CRUD operation for SecurityIncident entity:

/Users/ondrejchrbolka/Fei/Studium/NNPRO/KST-NNPRO-Bezpecnost-zeleznic/src/main/java/cz/semprace/bezpecnostzeleznic/model/SecurityIncident.java

**Comment by Domel303** [comment]
resolved in commit https://github.com/st55774/KST-NNPRO-Bezpecnost-zeleznic/commit/3ed4b76dbe03b983e0b4f5ca02b1531e250b6ef9
