### ISSUE TITLE
Link/unlink Subject entity with Damage

### ISSUE THREAD

**Issue by st55774** [st55774/KST-NNPRO-Bezpecnost-zeleznic#30]
- [ ] Create API for adding Subject to Damage.
- [ ] Create API for removing Subject from Damage.

**Comment by Domel303** [comment]
(untested) resolved in commit https://github.com/st55774/KST-NNPRO-Bezpecnost-zeleznic/commit/04bb69542917ad98c2c847d264be2101eba8b055
