### ISSUE TITLE
Edit API for registration of Administration or User of DS

### ISSUE THREAD

**Issue by st55774** [st55774/KST-NNPRO-Bezpecnost-zeleznic#32]
- [x] Edit/Add API of registration to support registration of Administration DS.
- [x] Edit/Add API of registration to support registration of User DS.
- [x] Secure situation that user has permission to create user.

**Comment by Domel303** [comment]
this functionality is already supported in the code. Creation of Administrator and User DS is in SignUpForm where there are String values of roles (ROLE_USER_DS, ROLE_ADMIN_DS, ROLE_ADMIN_SZ) which is transformated into role. 
Creation of user can be done with triggering ("api/auth/signup") and sending the form so user can create new user with this endpoint
