### ISSUE TITLE
Vytvoření číselníkové databáze pro vozy

### ISSUE THREAD

**Issue by st55774** [st55774/KST-NNPRO-Bezpecnost-zeleznic#36]
- [x] Je nutné se rozhodnout jestli daný číselník budeme řešit buď (nehodící píčovinu škrti @Domel303 nebo @st55425):
    - [x] Jako další entitu v našem databázovém modelu.
- [x] Vytvořit Spring job který bude udržovat konzistenci/aktuálnost vozů.
- [x] Ideálně naplnit zdrojovými daty.

Pro více informací kontaktovat @st52165 nebo @pavelkrivda (@pavlas123 )

**Comment by Domel303** [comment]
Spring job funguje tak, že všem vozům nastaví platnost do na aktuální čas a poté vygeneruje náhodnou váhu a uloží vozy s novým platnost od
