### ISSUE TITLE
Vymazat přebytečné entity z 1. fáze

### ISSUE THREAD

**Issue by st55774** [st55774/KST-NNPRO-Bezpecnost-zeleznic#37]
- [x] Vymazat entity jako lokomotiva, které už nemusí být součástí projektu (dle Vilíma moc složité).
- [x] Uvést ostatní entity, které byly ve vztahu se smazanými do konzistence dle EA modelu.
- [x] Upravit API které tyto informace poskytuje frontendu.
    Nově totiž Entita Wagon bude poskytovat i vozidla (souvisí s: #36)

![image](https://user-images.githubusercontent.com/57178559/145106055-208c756f-183b-4fea-9fe0-34c5c8be11da.png)

Obrázek pouze ilustrační...

**Comment by Domel303** [comment]
change the API or use annotations which will create the REST API ?

**Comment by Domel303** [comment]
API has been changed
