### ISSUE TITLE
Vytvoření nových entit na základě EA modelu

### ISSUE THREAD

**Issue by st55774** [st55774/KST-NNPRO-Bezpecnost-zeleznic#39]
- [x] Vytvoření entit se všemi potřebnými atributy.
- [x] Vytvoření číselníků.
- [x] V entitě **Files** chybí atribut pro samotný data (BLOB).

![image](https://user-images.githubusercontent.com/57178559/145106717-788adb6b-1d90-4b13-b039-d41389239d72.png)

Obrázek pouze ilustrační...

**Comment by Domel303** [comment]
Entity was added according to EA model
