### ISSUE TITLE
Vytvořit REST API pro nové entity

### ISSUE THREAD

**Issue by st55774** [st55774/KST-NNPRO-Bezpecnost-zeleznic#40]
@Domel303 Pro úsporu času bych zvážil použití: https://spring.io/guides/gs/accessing-data-rest/. Pomocí jedné anotace nad repository ti Spring vygeneruje i REST API. Na bezpečnost bych moc nedbal... uvidíme jak časově.

- [x] Udělat REST API nad nově vzniklými entitami.

**Comment by Domel303** [comment]
REST API for new entities is build with magicall annotations
